language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip --version
  - pip install coverage
  - pip install numpy

# execute any number of scripts before the test run.
before_script:
  - uname -a
  - printenv
  - pip list

# command to run tests
script:
  - date
  - ls -al
  - make collatz-tests
  - ls -al
  - make Collatz.html
  - ls -al
  - make Collatz.log
  - ls -al
  - make test
  - ls -al
  - make check
